name: keutech
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  supabase_flutter: ^2.5.0
  intl: ^0.19.0
  table_calendar: ^3.0.9
  image_picker: ^1.0.7
  fl_chart: ^0.68.0
  pdf: ^3.11.0
  path_provider: ^2.0.14
  printing: ^5.14.2

  # Icons untuk iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: "assets/images/logoSIA.png"
  min_sdk_android: 21
