name: keutech
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # DEKLARASI ASSETS (Diperbarui sesuai lokasi fisik Anda)
  assets:
    # Mengambil file logo yang berada langsung di folder 'assets'
    - assets/images/LogoSIA.png 
    # Mendeklarasikan folder fonts (tetap diperlukan)
    - assets/fonts/ 
  
  # DEKLARASI FONT POPPINS
  fonts:
    - family: Poppins
      fonts:
        # Deklarasikan semua varian font yang ingin Anda gunakan
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        # Anda bisa tambahkan Poppins-SemiBold.ttf, dll.